FEATURE_NAMES = ['Toe X Velocity', 'Center X Velocity', 'Heel X Velocity',
                 'Toe Y Velocity', 'Center Y Velocity', 'Heel Y Velocity',
                 'Toe X Acceleration', 'Center X Acceleration', 'Heel X Acceleration',
                 'Toe Y Acceleration', 'Center Y Acceleration', 'Heel Y Acceleration',
                 'Toe Height', 'Center Height', 'Heel Height',
                 'Toe Lateral', 'Center Lateral', 'Heel Lateral',
                 'Height Differential', 'Curl Distance']

FEAT_RANGES=['Fast   Slow    Fast',
             'Fast   Slow    Fast',
             'Fast   Slow    Fast',
             'Fast   Slow    Fast',
             'Fast   Slow    Fast',
             'Fast   Slow    Fast',
             'Accel Constant Decel',
             'Accel Constant Decel',
             'Accel Constant Decel',
             'Accel Constant Decel',
             'Accel Constant Decel',
             'Accel Constant Decel',
             'High            Low',
             'High            Low',
             'High            Low',
             'Away         Toward',
             'Away         Toward',
             'Away         Toward',
             'Angled         Flat',
             'Curled         Flat']

VID_FR = 2000